### ISSUE TITLE
Display animation when closing Modal

### ISSUE THREAD

**Issue by dannysanchez559** [dannysanchez559/poke-app#108]
**Is your feature request related to a problem? Please describe.**
Modal displays an animation upon opening, I think it would be a good small UI tweak to show this same animation, in reverse upon closing the modal. 

![image](https://user-images.githubusercontent.com/24641210/129101328-f5fa608a-0e33-4f30-9ca0-2317d7edc0d7.png)

**Comment by connielion** [comment]
Adding a modalCloseAnimaition useSpring does not work, possibly due to `react-modal`'s own styling(modal would still close quickly). Attempt to add causes lag when opening modal.
