### ISSUE TITLE
stop pokeapp background from scrolling when modal is open

### ISSUE THREAD

**Issue by dannysanchez559** [dannysanchez559/poke-app#114]
**Is your feature request related to a problem? Please describe.**
disable user being able to scroll background when modal is open

![image](https://user-images.githubusercontent.com/24641210/129120391-2c8b5f40-3f53-412b-873b-fab733c37627.png)

**Comment by connielion** [comment]
To conditionally apply `overflow: hidden` to `.pokeApp` div in `PokeApp`, we need to move the initialization of `modalIsOpen` to `PokeApp` from `PokeCard`, and that worsens the performance of the app and causes modal animation to lag etc.
