### ISSUE TITLE
Remove "/n" from Modal About description

### ISSUE THREAD

**Issue by dannysanchez559** [dannysanchez559/poke-app#92]
**Is your feature request related to a problem? Please describe.**
The pokeapi shows pokemon details text. The text string includes "/n" that doesn't display properly in the web page.

**Describe the solution you'd like**
Handle cases of "/n" to be replace with a space, " ".

![image](https://user-images.githubusercontent.com/24641210/128770846-c4a1ac84-3376-44d0-a3dc-293b5d438393.png)

**Comment by connielion** [comment]
Closing since adding Spinner seems to have fixed this.
